# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e243c69df9d51ec1f303e644bb3a875644c98dd681b3a3942edcca66957873255878655420c51a01cdbf04e0a6c54cb05d4a1088a3ab45462e63cdcc84310d

test:
  secret_key_base: a47181379064b92e0ceddeb993f7b922b2c13716299d0c063e3da1fe21588afadc749ab916449da6c3b4f1300cfb2d371e6a5b6afb6ac4b40841983cb93c1e90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
